name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

          npm install -g @angular/cli@17.3.17
          npm install --legacy-peer-deps

          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build Angular app
        run: |
          # Build for root domain (custom domain)
          ng build --configuration production --base-href="/"

          # Set the dist path variable
          APP_DIST=dist/free-tech-tools-app

          # GitHub Pages setup
          cp $APP_DIST/index.html $APP_DIST/404.html
          touch $APP_DIST/.nojekyll

          # Add CNAME for custom domain
          echo "freetechtools.com" > $APP_DIST/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/free-tech-tools-app'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
