name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          npm run build -- --configuration=production --base-href="/"
          # Create a 404.html file for GitHub Pages SPA routing
          cp dist/free-tech-tools-app/browser/index.html dist/free-tech-tools-app/browser/404.html
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/free-tech-tools-app/browser
          branch: gh-pages
          clean: true
